---
title: "Single-Trait Multi-Environment Analysis - NE Complete Model"
output: pdf_document
chunk_output_type: console
---
# Load BLUEs


Load BLUEs from grain yield (GY), grain moisture (GM) and number of ears (NE)

```{r eval=FALSE, message=FALSE}
BLUEs <- read.table("BLUEs.txt", sep = "\t", h = TRUE, stringsAsFactors = F)
```

Select the BLUEs from trait NE 

```{r eval=FALSE, message=FALSE}
library(dplyr)
BLUEs_NE <- select(BLUEs, c("H", "Env", "NE_BLUE"))
```


# Load H matrix

```{r eval=FALSE, message=FALSE}
load("Hinv.RData")
dim(AHAT.inv)
```


# Adjust the predictive model using MCMCglmm


Set the number of iterations, thin and burnin

```{r eval=FALSE, message=FALSE}
library(MCMCglmm)
nitt=30000
thin=5
burnin= 6000
Hinv = as(AHAT.inv,"dgCMatrix") # transform to sparse matrix
```

Declare the priori

```{r eval=FALSE, message=FALSE}
n.env = 4
prior.NonIformative.me <- list(R = list(V = diag(n.env)/n.env, n =0.002), 
                               G = list( G1 = list(V = diag(n.env)/n.env, n = 0.002)))
```


Adjust the predictive model 

```{r, eval=FALSE, message=FALSE}
complete.model.ME.NE = MCMCglmm(NE_BLUE ~ -1 + Env,
                               random= ~us(Env):H,
                               ginverse=list(H=Hinv),
                               rcov = ~ us(Env):units,
                               data = BLUEs_NE, 
                               prior=prior.NonIformative.me,
                               pr=TRUE,
                               nitt=nitt, thin=thin, burnin=burnin)


summary(complete.model.ME.NE) 
dim(complete.model.ME.NE$VCV) 

save.image("complete.model.ME.NE.RData")
  
```



