---
title: "Single-Trait Multi-Environment Analysis - GM CV1"
output: pdf_document
chunk_output_type: console
---
# Load BLUEs


Load BLUEs from grain yield (GY), grain moisture (GM) and number of ears (NE)

```{r eval=FALSE, message=FALSE}
BLUEs <- read.table("BLUEs.txt", sep = "\t", h = TRUE, stringsAsFactors = F)
```

Select the BLUEs from trait GM 

```{r eval=FALSE, message=FALSE}
library(dplyr)
BLUEs_GM <- select(BLUEs, c("H", "Env", "GM_BLUE"))
```

Create a column env_hybrid

```{r eval=FALSE, message=FALSE}
BLUEs_GM$env_hybrid <- paste("Env",BLUEs_GM$Env , sep = "", BLUEs_GM$H)
```

# Load Hinv matrix

```{r eval=FALSE, message=FALSE}
load("Hinv.RData")
dim(AHAT.inv)
```


# Adjust the predictive model using MCMCglmm


Set the number of iterations, thin and burnin

```{r eval=FALSE, message=FALSE}
library(MCMCglmm)
nitt=30000
thin=5
burnin=6000
Hinv = as(AHAT.inv,"dgCMatrix") # transform to sparse matrix
```

Declare the prior

```{r eval=FALSE, message=FALSE}
n.env = 4
prior.NonIformative.me <- list(R = list(V = diag(n.env)/n.env, n =0.002),
                               G = list( G1 = list(V = diag(n.env)/n.env, n = 0.002)))
```


Adjust the predictive model using a 5 folds cross-validation scheme

```{r, eval=FALSE, message=FALSE}
set.seed(156423) 
acc_mcmcglmm <- vector(length=5)
n_folds <- 1:5
sets<-sample(c(rep(n_folds, each=85))) # CV 5 folds

for(fold in n_folds){

  tst<- which(sets ==  fold) # separating the sets from test population
  names_hybrids_tst <- BLUEs_GM[tst,1, drop= FALSE]
  names_hybrids_tst_unique <- unique(names_hybrids_tst)
  yteste <- BLUEs_GM[which(BLUEs_GM$H %in% names_hybrids_tst_unique[,1]),]
  # separating the sets from training population
  '%!in%' <- function(x,y)!('%in%'(x,y))
  ytrn <- BLUEs_GM[which(BLUEs_GM$H %!in% names_hybrids_tst_unique[,1]),]
  dim(ytrn) 
 
  print(paste('Model STME.GM.CV1', fold))

  STME.GM.CV1 = MCMCglmm(GM_BLUE ~ -1 + Env,
            random= ~us(Env):H,
            ginverse=list(H=Hinv),
            rcov = ~ us(Env):units,
            data = ytrn, 
            prior=prior.NonIformative.me,
            pr=TRUE,
            nitt=nitt, thin=thin, burnin=burnin)
  
   

  blups = colMeans(STME.GM.CV1$Sol)
  predicted_gm = data.frame(env_hybrid=gsub(".H.H","H",names(blups)),blups)
  predicted_and_observed_gm = merge(BLUEs_GM,predicted_gm,by="env_hybrid")
  final_gm = predicted_and_observed_gm[tst,]
  acc_mcmcglmm[fold] <- cor(final_gm[,4],final_gm[,5])
}  

save.image("STME_GM_CV1.RData")  
```



