---
title: "Single-Trait Multi-Environment Analysis - NE CV"
output: pdf_document
chunk_output_type: console
---
# Load BLUEs


Load BLUEs from grain yield (GY), grain moisture (GM) and number of ears (NE)

```{r eval=FALSE, message=FALSE}
BLUEs <- read.table("BLUEs.txt", sep = "\t", h = TRUE, stringsAsFactors = F)
```

Select the BLUEs from trait NE 

```{r eval=FALSE, message=FALSE}
library(dplyr)
BLUEs_NE <- select(BLUEs, c("H", "Env", "NE_BLUE"))
```

Create a column env_hybrid

```{r eval=FALSE, message=FALSE}
BLUEs_NE$env_hybrid <- paste("Env",BLUEs_NE$Env , sep = "", BLUEs_NE$H)
```

# Load H matrix

```{r eval=FALSE, message=FALSE}
load("Hinv.RData")
dim(AHAT.inv)
```


# Adjust the predictive model using MCMCglmm


Set the number of iterations, thin and burnin

```{r eval=FALSE, message=FALSE}
library(MCMCglmm)
nitt=30000
thin=5
burnin=6000
Hinv = as(AHAT.inv,"dgCMatrix") # transform to sparse matrix
```

Declare the priori

```{r eval=FALSE, message=FALSE}
n.env = 4
prior.NonIformative.me <- list(R = list(V = diag(n.env)/n.env, n =0.002), 
                               G = list( G1 = list(V = diag(n.env)/n.env, n = 0.002)))
```


Adjust the predictive model using a 5 folds cross-validation scheme

```{r, eval=FALSE, message=FALSE}
set.seed(156423) 
acc_mcmcglmm <- vector(length=5)
n_folds <- 1:5
sets<-sample(c(rep(n_folds, each=85))) # CV 5 folds

for(fold in n_folds){
  tst<- which(sets ==  fold) # separating the sets from test population
  
  ytest <- BLUEs_NE[tst, c(1,3) ,drop= FALSE]
 
  print(paste('Model STME.NE', fold))

  STME.NE = MCMCglmm(NE_BLUE ~ -1 + Env,
            random= ~us(Env):H,
            ginverse=list(H=Hinv),
            rcov = ~ us(Env):units,
            data = BLUEs_NE[-tst,], 
            prior=prior.NonIformative.me,
            pr=TRUE,
            nitt=nitt, thin=thin, burnin=burnin)


blups = colMeans(STME.NE$Sol)
predicted_NE = data.frame(env_hybrid=gsub(".H.H","H",names(blups)),blups)
predicted_and_observed_NE = merge(BLUEs_NE,predicted_NE,by="env_hybrid")
final_NE = predicted_and_observed_NE[tst,]
acc_mcmcglmm[fold] <- cor(final_NE[,4],final_NE[,5])
}  

save.image("STME_NE_CV.RData")  
```



